# Glacier Peak Scouting Report - 20107

In [1]:
import pandas as pd
import sqlalchemy as sa
import sys

# Add IRScout to project path. Note: unless your  name is not Stacy, you
#   probably need to modify this file path
project_path = ('C:\Users\stacy\OneDrive\Projects\scouting17'
                '\irsScouting2017\Server')
sys.path.append(project_path)

# Setup Jupyter for displaying plots
%matplotlib notebook

In [2]:
# Get a database connection
connection_string = ('postgresql://irs1318:irs1318'
                     '@localhost:5432/scouting')
engine = sa.create_engine(connection_string)
conn = engine.connect()

In [3]:
import scouting.output as out
import scouting.event as evt
evt.EventDal.set_current_event('wasno')
evt.EventDal.get_current_event()

u'wasno'

In [4]:
out.get_report()

C:/Users/stacy/Desktop/Report_wasno2017Mar25_175235.xlsx

In [5]:
sql_measures = sa.text(
    "SELECT events.name AS event, matches.name AS match, levels.name AS level, dates.name AS date, "
    "teams.name AS team, alliances.name AS alliance, "
    "stations.name AS station, phases.name AS phase, actors.name AS actor, tasks.name AS task, "
    "measures.capability AS capability, measures.successes as successes, measures.attempts AS attempts, "
    "measures.cycle_times as cycle_times, measuretypes.name AS measuretype, reasons.name AS reason, "
    "attempts.name AS attempt "
    "FROM ((((((((((((measures FULL OUTER JOIN teams ON measures.team_id=teams.id) "
    "LEFT JOIN events ON measures.event_id=events.id) "
    "LEFT JOIN matches ON measures.match_id=matches.id) "
    "LEFT JOIN levels ON measures.level_id=levels.id) "
    "LEFT JOIN dates ON measures.date_id=dates.id) "
    "LEFT JOIN alliances ON measures.alliance_id=alliances.id) "
    "LEFT JOIN stations ON measures.station_id=stations.id) "
    "LEFT JOIN phases ON measures.phase_id=phases.id) "
    "LEFT JOIN actors ON measures.actor_id=actors.id) "
    "LEFT JOIN tasks ON measures.task_id=tasks.id) "
    "LEFT JOIN reasons ON measures.reason_id=reasons.id) "
    "LEFT JOIN measuretypes ON measures.measuretype_id=measuretypes.id) "
    "LEFT JOIN attempts ON measures.attempt_id=attempts.id "
    "WHERE events.name='wasno' AND actors.name='robot';")
measures = pd.read_sql(sql_measures, conn)
measures.query("team == '1318'").query("task == 'pushTouchPad'").query("phase == 'finish'")

,event,match,level,date,team,alliance,station,phase,actor,task,capability,successes,attempts,cycle_times,measuretype,reason,attempt
558,wasno,002-q,qual,2017-03-25T11:07:00,1318,blue,3,finish,robot,pushTouchPad,0,1,1,0,boolean,na,summary
1114,wasno,012-q,qual,2017-03-25T12:17:00,1318,blue,3,finish,robot,pushTouchPad,0,1,1,0,boolean,na,summary
1364,wasno,017-q,qual,2017-03-25T12:52:00,1318,blue,3,finish,robot,pushTouchPad,0,1,1,0,boolean,na,summary
1713,wasno,023-q,qual,2017-03-25T14:34:00,1318,red,3,finish,robot,pushTouchPad,0,1,1,0,boolean,na,summary
2098,wasno,030-q,qual,2017-03-25T15:23:00,1318,red,2,finish,robot,pushTouchPad,0,1,1,0,boolean,na,summary

# Create the Dataframe

In [6]:
# Get Sums for non-alliance data
evt = 'waamv'
sel_sums = sa.text(
    "SELECT teams.name AS team, phases.name AS phase, tasks.name AS task, "
    "actors.name AS actor, "
    "SUM(successes) AS sum_successes, SUM(attempts) AS sum_attempts "
    "FROM ((((teams FULL OUTER JOIN measures ON teams.id=measures.team_id) "
    "LEFT JOIN tasks ON tasks.id = measures.task_id) "
    "LEFT JOIN phases ON phases.id = measures.phase_id) "
    "LEFT JOIN events ON events.id = measures.event_id) "
    "LEFT JOIN actors ON actors.id = measures.actor_id "
    "WHERE events.name = '" + evt + "' AND actors.name<>'alliance' "
    "GROUP BY teams.name, tasks.name, phases.name, actors.name "
    "ORDER BY teams.name, phases.name, tasks.name, actors.name;")
df_sums = pd.read_sql(sel_sums, conn)
    
df_sums = df_sums.set_index(['team', 'phase', 'actor', 'task'])
df_sums = df_sums.stack()
df_sums = df_sums.unstack([1, 2, 3, 4])
df_sums = df_sums.sort_index(axis = 1, level = [0, 1, 2])

for col in df_sums:
    if col[3] == 'sum_successes':
        phase = col[0]
        actor = col[1]
        task = col[2]
        percent = df_sums[(phase, actor, task, 'sum_successes')] /\
                  df_sums[(phase, actor, task, 'sum_attempts')]
        df_sums.insert(0, (phase, actor, task, 'percent'), percent)
        
df_sums = df_sums.sort_index(axis = 1, level = [0,1,2])
df_sums.head(5)

phase          auto                                                     \
actor         pilot                                 robot
task       dropGear                      holdFuelCapacity
      sum_successes sum_attempts percent    sum_successes sum_attempts
team
1258            NaN          NaN     NaN             11.0         10.0
1294            NaN          NaN     NaN              3.0          0.0
1318            NaN          NaN     NaN              8.0          1.0
1899            NaN          NaN     NaN              0.0          0.0
1983            NaN          NaN     NaN              0.0          0.0

phase                                                                 ...    \
actor                                                                 ...
task                 holdGear                          moveBaseline   ...
        percent sum_successes sum_attempts    percent sum_successes   ...
team                                                                  ...
1258   1.100000           8.0          1.0   8.000000           6.0   ...
1294        inf          10.0          1.0  10.000000           7.0   ...
1318   8.000000          10.0          1.0  10.000000           6.0   ...
1899        NaN           7.0          0.0        inf           2.0   ...
1983        NaN          12.0          0.0        inf           7.0   ...

phase              teleop                                       \
actor               robot
task  pickupGearRetrieval     placeGear
                  percent sum_successes sum_attempts   percent
team
1258                  1.0          14.0         16.0  0.875000
1294                  1.0          21.0         21.0  1.000000
1318                  1.0          15.0         22.0  0.681818
1899                  1.0          14.0         19.0  0.736842
1983                  1.0          19.0         22.0  0.863636

phase                                                                     \
actor
task  shootHighBoiler                        shootLowBoiler
        sum_successes sum_attempts   percent  sum_successes sum_attempts
team
1258             20.0         20.0  1.000000            3.0          3.0
1294              2.0          6.0  0.333333            NaN          NaN
1318              2.0         10.0  0.200000            NaN          NaN
1899              0.0          0.0       NaN            NaN          NaN
1983              0.0          0.0       NaN            NaN          NaN

phase
actor
task
      percent
team
1258      1.0
1294      NaN
1318      NaN
1899      NaN
1983      NaN

[5 rows x 105 columns]

# Plot Some Data

In [7]:
placeGears = df_sums.xs('placeGear', axis = 1, level = 2, drop_level = False)
placeGears = placeGears.xs('sum_successes', axis = 1, level = 3, drop_level = False)
placeGears['total'] = placeGears.sum(axis = 1)
placeGears = placeGears.sort_values('total', axis = 0, ascending = False)
del placeGears['total']
placeGears[[1,0]].plot.bar(stacked = True, sort_columns = 1, title = 'Total Gears Placed', colormap = 'bwr')

In [8]:
lastmatch = sa.text(
"SELECT matches.name AS match FROM matches RIGHT JOIN measures on matches.id=measures.match_id "
    "ORDER BY matches.name DESC;"
)
df_lastmatch = pd.read_sql(lastmatch, conn)
df_lastmatch.iloc[0]

match    na
Name: 0, dtype: object

In [9]:
sched = sa.text(
"SELECT * FROM schedules "
"WHERE event = 'wasno';"
)

df_sched = pd.read_sql(sched, conn)
df_sched

       id                 date  event level  match alliance  team station
0    3854  2017-03-25T12:31:00  wasno  qual  014-q      red  2903       3
1    3855  2017-03-25T12:31:00  wasno  qual  014-q     blue  4683       1
2    3856  2017-03-25T12:31:00  wasno  qual  014-q     blue  2412       2
3    3857  2017-03-25T12:31:00  wasno  qual  014-q     blue  5588       3
4    3858  2017-03-25T12:38:00  wasno  qual  015-q      red  4911       1
5    3859  2017-03-25T12:38:00  wasno  qual  015-q      red  1294       2
6    3860  2017-03-25T12:38:00  wasno  qual  015-q      red  4469       3
7    3861  2017-03-25T12:38:00  wasno  qual  015-q     blue  5748       1
8    3862  2017-03-25T12:38:00  wasno  qual  015-q     blue  6503       2
9    3863  2017-03-25T12:38:00  wasno  qual  015-q     blue   949       3
10   3864  2017-03-25T12:45:00  wasno  qual  016-q      red  2910       1
11   3865  2017-03-25T12:45:00  wasno  qual  016-q      red  5803       2
12   3866  2017-03-25T12:45:00  wasno  qual  016-q      red  3218       3
13   3867  2017-03-25T12:45:00  wasno  qual  016-q     blue  4682       1
14   3868  2017-03-25T12:45:00  wasno  qual  016-q     blue  3663       2
15   3869  2017-03-25T12:45:00  wasno  qual  016-q     blue  4915       3
16   3870  2017-03-25T12:52:00  wasno  qual  017-q      red  5683       1
17   3871  2017-03-25T12:52:00  wasno  qual  017-q      red  5941       2
18   3872  2017-03-25T12:52:00  wasno  qual  017-q      red  1778       3
19   3873  2017-03-25T12:52:00  wasno  qual  017-q     blue  2555       1
20   3874  2017-03-25T12:52:00  wasno  qual  017-q     blue  4512       2
21   3875  2017-03-25T12:52:00  wasno  qual  017-q     blue  1318       3
22   3876  2017-03-25T13:59:00  wasno  qual  018-q      red  4683       1
23   3877  2017-03-25T13:59:00  wasno  qual  018-q      red  4180       2
24   3878  2017-03-25T13:59:00  wasno  qual  018-q      red  2930       3
25   3879  2017-03-25T13:59:00  wasno  qual  018-q     blue  2522       1
26   3880  2017-03-25T13:59:00  wasno  qual  018-q     blue  4681       2
27   3881  2017-03-25T13:59:00  wasno  qual  018-q     blue  5827       3
28   3882  2017-03-25T14:06:00  wasno  qual  019-q      red  2928       1
29   3883  2017-03-25T14:06:00  wasno  qual  019-q      red  4077       2
..    ...                  ...    ...   ...    ...      ...   ...     ...
451  3824  2017-03-25T11:56:00  wasno  qual  009-q      red  4089       3
452  3825  2017-03-25T11:56:00  wasno  qual  009-q     blue  4180       1
453  3826  2017-03-25T11:56:00  wasno  qual  009-q     blue  4682       2
454  3827  2017-03-25T11:56:00  wasno  qual  009-q     blue  2928       3
455  3828  2017-03-25T12:03:00  wasno  qual  010-q      red  5803       1
456  3829  2017-03-25T12:03:00  wasno  qual  010-q      red   492       2
457  3830  2017-03-25T12:03:00  wasno  qual  010-q      red  1899       3
458  3831  2017-03-25T12:03:00  wasno  qual  010-q     blue  4469       1
459  3832  2017-03-25T12:03:00  wasno  qual  010-q     blue  2605       2
460  3833  2017-03-25T12:03:00  wasno  qual  010-q     blue  4681       3
461  3834  2017-03-25T12:10:00  wasno  qual  011-q      red   949       1
462  3835  2017-03-25T12:10:00  wasno  qual  011-q      red  2555       2
463  3836  2017-03-25T12:10:00  wasno  qual  011-q      red  1778       3
464  3837  2017-03-25T12:10:00  wasno  qual  011-q     blue  3663       1
465  3838  2017-03-25T12:10:00  wasno  qual  011-q     blue  2557       2
466  3839  2017-03-25T12:10:00  wasno  qual  011-q     blue  5941       3
467  3840  2017-03-25T12:17:00  wasno  qual  012-q      red  5827       1
468  3841  2017-03-25T12:17:00  wasno  qual  012-q      red  5748       2
469  3842  2017-03-25T12:17:00  wasno  qual  012-q      red  1294       3
470  3843  2017-03-25T12:17:00  wasno  qual  012-q     blue  5495       1
471  3844  2017-03-25T12:17:00  wasno  qual  012-q     blue  2522       2
472  3845  2017-03-25T12:17:00  wasno  qual  012-q     blue  1318       3
473  3846  2017-03-25T12:24:00  wasno  qual  013-q      red  3070       1
474  3847  2017-03-25T12:24:00  wasno  qual  013-q      red  4512       2
475  3848  2017-03-25T12:24:00  wasno  qual  013-q      red  3218       3
476  3849  2017-03-25T12:24:00  wasno  qual  013-q     blue  4077       1
477  3850  2017-03-25T12:24:00  wasno  qual  013-q     blue  2930       2
478  3851  2017-03-25T12:24:00  wasno  qual  013-q     blue  3268       3
479  3852  2017-03-25T12:31:00  wasno  qual  014-q      red  4089       1
480  3853  2017-03-25T12:31:00  wasno  qual  014-q      red  1899       2

[481 rows x 8 columns]

In [10]:
sql = sa.text(
"with current as (select s.match, date from schedules sched, status s "
"where sched.event = s.event and sched.match = s.match limit 1 ) "
"select * from ( "
"    select row_number() over (partition by team order by sched.date desc) as r, "
"    sched.* "
"    from schedules sched, current c "
"    where sched.date <= c.date "
") row_schedule "
"    where "
"    row_schedule.r <= 3 "
"    order by team, date desc;")
lb_df = pd.read_sql(sql, conn)
lb_df

     r    id                 date  event level  match alliance  team station
0    1  3971  2017-03-25T15:44:00  wasno  qual  033-q     blue  1294       3
1    2  3928  2017-03-25T14:55:00  wasno  qual  026-q     blue  1294       2
2    3  3859  2017-03-25T12:38:00  wasno  qual  015-q      red  1294       2
3    1  3949  2017-03-25T15:23:00  wasno  qual  030-q      red  1318       2
4    2  3908  2017-03-25T14:34:00  wasno  qual  023-q      red  1318       3
5    3  3875  2017-03-25T12:52:00  wasno  qual  017-q     blue  1318       3
6    1  3985  2017-03-25T16:05:00  wasno  qual  036-q      red  1778       2
7    2  3946  2017-03-25T15:16:00  wasno  qual  029-q     blue  1778       2
8    3  3915  2017-03-25T14:41:00  wasno  qual  024-q     blue  1778       1
9    1  3954  2017-03-25T15:30:00  wasno  qual  031-q      red  1899       1
10   2  3913  2017-03-25T14:41:00  wasno  qual  024-q      red  1899       2
11   3  3853  2017-03-25T12:31:00  wasno  qual  014-q      red  1899       2
12   1  3992  2017-03-25T16:12:00  wasno  qual  037-q      red  1983       3
13   2  3945  2017-03-25T15:16:00  wasno  qual  029-q     blue  1983       1
14   3  3906  2017-03-25T14:34:00  wasno  qual  023-q      red  1983       1
15   1  4001  2017-03-25T16:19:00  wasno  qual  038-q     blue  2412       3
16   2  3972  2017-03-25T15:51:00  wasno  qual  034-q      red  2412       1
17   3  3896  2017-03-25T14:20:00  wasno  qual  021-q      red  2412       3
18   1  3953  2017-03-25T15:23:00  wasno  qual  030-q     blue  2522       3
19   2  3902  2017-03-25T14:27:00  wasno  qual  022-q      red  2522       3
20   3  3879  2017-03-25T13:59:00  wasno  qual  018-q     blue  2522       1
21   1  3978  2017-03-25T15:58:00  wasno  qual  035-q      red  2555       1
22   2  3961  2017-03-25T15:37:00  wasno  qual  032-q      red  2555       2
23   3  3900  2017-03-25T14:27:00  wasno  qual  022-q      red  2555       1
24   1  3996  2017-03-25T16:19:00  wasno  qual  038-q      red  2557       1
25   2  3931  2017-03-25T15:02:00  wasno  qual  027-q      red  2557       2
26   3  3917  2017-03-25T14:41:00  wasno  qual  024-q     blue  2557       3
27   1  3943  2017-03-25T15:16:00  wasno  qual  029-q      red  2605       2
28   2  3919  2017-03-25T14:48:00  wasno  qual  025-q      red  2605       2
29   3  3884  2017-03-25T14:06:00  wasno  qual  019-q      red  2605       3
..  ..   ...                  ...    ...   ...    ...      ...   ...     ...
90   1  3988  2017-03-25T16:05:00  wasno  qual  036-q     blue   492       2
91   2  3967  2017-03-25T15:44:00  wasno  qual  033-q      red   492       2
92   3  3909  2017-03-25T14:34:00  wasno  qual  023-q     blue   492       1
93   1  3995  2017-03-25T16:12:00  wasno  qual  037-q     blue  5495       3
94   2  3975  2017-03-25T15:51:00  wasno  qual  034-q     blue  5495       1
95   3  3925  2017-03-25T14:55:00  wasno  qual  026-q      red  5495       2
96   1  3982  2017-03-25T15:58:00  wasno  qual  035-q     blue  5588       2
97   2  3948  2017-03-25T15:23:00  wasno  qual  030-q      red  5588       1
98   3  3932  2017-03-25T15:02:00  wasno  qual  027-q      red  5588       3
99   1  3993  2017-03-25T16:12:00  wasno  qual  037-q     blue  5683       1
100  2  3938  2017-03-25T15:09:00  wasno  qual  028-q      red  5683       3
101  3  3899  2017-03-25T14:20:00  wasno  qual  021-q     blue  5683       3
102  1  3980  2017-03-25T15:58:00  wasno  qual  035-q      red  5748       3
103  2  3944  2017-03-25T15:16:00  wasno  qual  029-q      red  5748       3
104  3  3898  2017-03-25T14:20:00  wasno  qual  021-q     blue  5748       2
105  1  3974  2017-03-25T15:51:00  wasno  qual  034-q      red  5803       3
106  2  3935  2017-03-25T15:02:00  wasno  qual  027-q     blue  5803       3
107  3  3901  2017-03-25T14:27:00  wasno  qual  022-q      red  5803       2
108  1  3973  2017-03-25T15:51:00  wasno  qual  034-q      red  5827       2
109  2  3940  2017-03-25T15:09:00  wasno  qual  028-q     blue  5827       2
110  3  3914  2017-03-25T14:41:00  wasno  qual  024-q      red  5827       3
111  1  3990  2017-03-25T16:12:00  wasno  qual  037-q      red  5941       1
112  2  3957  2017-03-25T15:30:00  wasno  qual  031-q     blue  5941       1
113  3  3927  2017-03-25T14:55:00  wasno  qual  026-q     blue  5941       1
114  1  3987  2017-03-25T16:05:00  wasno  qual  036-q     blue  6503       1
115  2  3959  2017-03-25T15:30:00  wasno  qual  031-q     blue  6503       3
116  3  3903  2017-03-25T14:27:00  wasno  qual  022-q     blue  6503       1
117  1  3997  2017-03-25T16:19:00  wasno  qual  038-q      red   949       2
118  2  3970  2017-03-25T15:44:00  wasno  qual  033-q     blue   949       2
119  3  3918  2017-03-25T14:48:00  wasno  qual  025-q      red   949       1

[120 rows x 9 columns]

In [11]:
num_matches = 12
mtchs = sa.text(
    "with current AS (SELECT s.match, date from schedules sched, "
    "status s WHERE sched.event = s.event "
    "AND sched.match = s.match limit 1 ), "

    "recent_matches as ( SELECT * FROM ( "
    "SELECT row_number() over (partition by team order by sched.date desc) as r, "
    " sched.* from schedules sched, current c WHERE sched.date <= c.date )"
    " row_schedule WHERE row_schedule.r <= " + str(num_matches) + " ORDER by team, date desc), "

    "team_match_count as ( "
        "select team, count(team) as team_matches from recent_matches group by team"
              ") "
    "SELECT * FROM team_match_count;")
df = pd.read_sql(mtchs, conn)
df

    team  team_matches
0   1294             5
1   3070             6
2   2412             6
3   2903             5
4   4681             6
5   5588             6
6   2557             6
7   6503             6
8   2928             6
9   2605             5
10  1983             6
11  3268             5
12  3663             5
13   492             6
14  5495             6
15  5803             6
16  2976             6
17  3218             6
18  1778             6
19  4469             6
20  1318             5
21  4089             5
22  5748             6
23  4682             5
24  4077             6
25  5827             6
26  4512             5
27  4309             6
28  1899             5
29  4683             5
30  2522             5
31  2910             6
32  5683             6
33  4180             6
34  5941             6
35  2930             6
36  2555             6
37   949             6
38  4915             6
39  4911             6

In [12]:
num_matches = 12
mtchs = sa.text(
    "with current AS (SELECT s.match, date from schedules sched, "
    "status s WHERE sched.event = s.event "
    "AND sched.match = s.match limit 1 ), "

    "recent_matches as ( SELECT * FROM ( "
    "SELECT row_number() over (partition by team order by sched.date desc) as r, "
    " sched.* from schedules sched, current c WHERE sched.date <= c.date )"
    " row_schedule WHERE row_schedule.r <= " + str(num_matches) + " ORDER by team, date desc), "

    "team_match_count as ( "
        "select team, count(team) as team_matches from recent_matches group by team"
              ") "
    "SELECT * FROM recent_matches;")
df = pd.read_sql(mtchs, conn)
df

     r    id                 date  event level  match alliance  team station
0    1  3971  2017-03-25T15:44:00  wasno  qual  033-q     blue  1294       3
1    2  3928  2017-03-25T14:55:00  wasno  qual  026-q     blue  1294       2
2    3  3859  2017-03-25T12:38:00  wasno  qual  015-q      red  1294       2
3    4  3842  2017-03-25T12:17:00  wasno  qual  012-q      red  1294       3
4    5  3815  2017-03-25T11:42:00  wasno  qual  007-q     blue  1294       3
5    1  3949  2017-03-25T15:23:00  wasno  qual  030-q      red  1318       2
6    2  3908  2017-03-25T14:34:00  wasno  qual  023-q      red  1318       3
7    3  3875  2017-03-25T12:52:00  wasno  qual  017-q     blue  1318       3
8    4  3845  2017-03-25T12:17:00  wasno  qual  012-q     blue  1318       3
9    5  3785  2017-03-25T11:07:00  wasno  qual  002-q     blue  1318       3
10   1  3985  2017-03-25T16:05:00  wasno  qual  036-q      red  1778       2
11   2  3946  2017-03-25T15:16:00  wasno  qual  029-q     blue  1778       2
12   3  3915  2017-03-25T14:41:00  wasno  qual  024-q     blue  1778       1
13   4  3872  2017-03-25T12:52:00  wasno  qual  017-q      red  1778       3
14   5  3836  2017-03-25T12:10:00  wasno  qual  011-q      red  1778       3
15   6  3812  2017-03-25T11:42:00  wasno  qual  007-q      red  1778       3
16   1  3954  2017-03-25T15:30:00  wasno  qual  031-q      red  1899       1
17   2  3913  2017-03-25T14:41:00  wasno  qual  024-q      red  1899       2
18   3  3853  2017-03-25T12:31:00  wasno  qual  014-q      red  1899       2
19   4  3830  2017-03-25T12:03:00  wasno  qual  010-q      red  1899       3
20   5  3798  2017-03-25T11:28:00  wasno  qual  005-q      red  1899       1
21   1  3992  2017-03-25T16:12:00  wasno  qual  037-q      red  1983       3
22   2  3945  2017-03-25T15:16:00  wasno  qual  029-q     blue  1983       1
23   3  3906  2017-03-25T14:34:00  wasno  qual  023-q      red  1983       1
24   4  3892  2017-03-25T14:13:00  wasno  qual  020-q     blue  1983       2
25   5  3822  2017-03-25T11:56:00  wasno  qual  009-q      red  1983       1
26   6  3801  2017-03-25T11:28:00  wasno  qual  005-q     blue  1983       1
27   1  4001  2017-03-25T16:19:00  wasno  qual  038-q     blue  2412       3
28   2  3972  2017-03-25T15:51:00  wasno  qual  034-q      red  2412       1
29   3  3896  2017-03-25T14:20:00  wasno  qual  021-q      red  2412       3
..  ..   ...                  ...    ...   ...    ...      ...   ...     ...
198  1  3974  2017-03-25T15:51:00  wasno  qual  034-q      red  5803       3
199  2  3935  2017-03-25T15:02:00  wasno  qual  027-q     blue  5803       3
200  3  3901  2017-03-25T14:27:00  wasno  qual  022-q      red  5803       2
201  4  3865  2017-03-25T12:45:00  wasno  qual  016-q      red  5803       2
202  5  3828  2017-03-25T12:03:00  wasno  qual  010-q      red  5803       1
203  6  3809  2017-03-25T11:35:00  wasno  qual  006-q     blue  5803       3
204  1  3973  2017-03-25T15:51:00  wasno  qual  034-q      red  5827       2
205  2  3940  2017-03-25T15:09:00  wasno  qual  028-q     blue  5827       2
206  3  3914  2017-03-25T14:41:00  wasno  qual  024-q      red  5827       3
207  4  3881  2017-03-25T13:59:00  wasno  qual  018-q     blue  5827       3
208  5  3840  2017-03-25T12:17:00  wasno  qual  012-q      red  5827       1
209  6  3804  2017-03-25T11:35:00  wasno  qual  006-q      red  5827       1
210  1  3990  2017-03-25T16:12:00  wasno  qual  037-q      red  5941       1
211  2  3957  2017-03-25T15:30:00  wasno  qual  031-q     blue  5941       1
212  3  3927  2017-03-25T14:55:00  wasno  qual  026-q     blue  5941       1
213  4  3871  2017-03-25T12:52:00  wasno  qual  017-q      red  5941       2
214  5  3839  2017-03-25T12:10:00  wasno  qual  011-q     blue  5941       3
215  6  3799  2017-03-25T11:28:00  wasno  qual  005-q      red  5941       2
216  1  3987  2017-03-25T16:05:00  wasno  qual  036-q     blue  6503       1
217  2  3959  2017-03-25T15:30:00  wasno  qual  031-q     blue  6503       3
218  3  3903  2017-03-25T14:27:00  wasno  qual  022-q     blue  6503       1
219  4  3862  2017-03-25T12:38:00  wasno  qual  015-q     blue  6503       2
220  5  3823  2017-03-25T11:56:00  wasno  qual  009-q      red  6503       2
221  6  3781  2017-03-25T11:07:00  wasno  qual  002-q      red  6503       2
222  1  3997  2017-03-25T16:19:00  wasno  qual  038-q      red   949       2
223  2  3970  2017-03-25T15:44:00  wasno  qual  033-q     blue   949       2
224  3  3918  2017-03-25T14:48:00  wasno  qual  025-q      red   949       1
225  4  3863  2017-03-25T12:38:00  wasno  qual  015-q     blue   949       3
226  5  3834  2017-03-25T12:10:00  wasno  qual  011-q      red   949       1
227  6  3807  2017-03-25T11:35:00  wasno  qual  006-q     blue   949       1

[228 rows x 9 columns]

In [13]:
# Check Query
num_matches = 12
evt = 'wasno'
select_sum = sa.text(
"with current AS (SELECT s.match, date from schedules sched, "
"status s WHERE sched.event = s.event "
"AND sched.match = s.match limit 1 ), "

"recent_matches as ( SELECT * FROM ( "
"SELECT row_number() over (partition by team order by sched.date desc) as r, "
" sched.* from schedules sched, current c WHERE sched.date <= c.date )"
" row_schedule WHERE row_schedule.r <= " + str(num_matches) + " ORDER by team, date desc), "

"team_match_count as ( "
    "select team, count(team) as team_matches from recent_matches group by team"
          ") "

"SELECT teams.name AS team, phases.name AS phase, tasks.name AS task, actors.name AS actor, "
"MAX(team_match_count.team_matches) AS matches, "
"SUM(successes) AS sum_successes, SUM(attempts) AS sum_attempts, AVG(cycle_times) "
"FROM ((((teams FULL OUTER JOIN measures ON teams.id=measures.team_id) "
"LEFT JOIN tasks ON tasks.id = measures.task_id) "
"LEFT JOIN phases ON phases.id = measures.phase_id) "
"LEFT JOIN events ON events.id = measures.event_id) "
"LEFT JOIN actors ON actors.id = measures.actor_id "
"LEFT JOIN matches ON matches.id = measures.match_id "
"LEFT JOIN team_match_count ON team_match_count.team = teams.name "
"RIGHT JOIN recent_matches ON recent_matches.match = matches.name AND team_match_count.team = teams.name "
    "AND recent_matches.team = team_match_count.team "
"WHERE events.name = '" + evt + "' AND actors.name<> 'alliance' "
"GROUP BY teams.name, tasks.name, phases.name, actors.name "
"ORDER BY teams.name, phases.name, tasks.name, actors.name;")
df = pd.read_sql(select_sum, conn)
df

,team,phase,task,actor,matches,sum_successes,sum_attempts,avg
0,1294,auto,dropGear,pilot,5,0,0,0.0
1,1294,auto,holdFuelCapacity,robot,5,2,2,0.0
2,1294,auto,holdGear,robot,5,4,4,0.0
3,1294,auto,moveBaseline,robot,5,4,7,0.0
4,1294,auto,placeGear,robot,5,3,4,0.0
5,1294,auto,startingLocation,robot,5,0,0,0.0
6,1294,finish,climbRope,robot,5,35,35,0.0
7,1294,finish,maintainContact,robot,5,4,4,0.0
8,1294,finish,pushTouchPad,robot,5,5,5,0.0
9,1294,teleop,pickupFuelFloor,robot,5,0,0,0.0
10,1294,teleop,pickupGearFloor,robot,5,0,0,0.0
11,1294,teleop,pickupGearRetrival,robot,5,5,5,0.0
12,1294,teleop,placeGear,robot,5,17,28,0.0
13,1294,teleop,shootHighBoiler,robot,5,1,6,0.0
14,1318,auto,dropGear,pilot,5,0,0,0.0
15,1318,auto,holdFuelCapacity,robot,5,2,2,0.0
16,1318,auto,holdGear,robot,5,3,3,0.0
17,1318,auto,moveBaseline,robot,5,4,7,0.0
18,1318,auto,placeGear,robot,5,2,6,0.0
19,1318,auto,shootHighBoiler,robot,5,6,21,0.0
20,1318,auto,startingLocation,robot,5,0,0,0.0
21,1318,finish,climbRope,robot,5,15,15,0.0
22,1318,finish,maintainContact,robot,5,5,5,0.0
23,1318,finish,pushTouchPad,robot,5,5,5,0.0
24,1318,teleop,pickupFuelFloor,robot,5,2,2,0.0
25,1318,teleop,pickupFuelHopper,robot,5,2,2,0.0
26,1318,teleop,pickupFuelRetrival,robot,5,1,1,0.0
27,1318,teleop,pickupGearFloor,robot,5,4,4,0.0
28,1318,teleop,pickupGearRetrival,robot,5,1,1,0.0
29,1318,teleop,placeGear,robot,5,8,11,0.0
...,...,...,...,...,...,...,...,...
536,5941,teleop,pickupFuelFloor,robot,6,0,0,0.0
537,5941,teleop,pickupGearFloor,robot,6,0,0,0.0
538,5941,teleop,pickupGearRetrival,robot,6,4,4,0.0
539,5941,teleop,placeGear,robot,6,12,20,0.0
540,5941,teleop,shootLowBoiler,robot,6,0,4,0.0
541,6503,auto,holdFuelCapacity,robot,6,0,0,0.0
542,6503,auto,holdGear,robot,6,6,6,0.0
543,6503,auto,moveBaseline,robot,6,6,9,0.0
544,6503,auto,placeGear,robot,6,0,1,0.0
545,6503,auto,startingLocation,robot,6,0,0,0.0
546,6503,finish,climbRope,robot,6,6,6,0.0
547,6503,finish,disabled,robot,6,1,1,0.0
548,6503,finish,maintainContact,robot,6,1,1,0.0
549,6503,finish,pushTouchPad,robot,6,2,2,0.0
550,6503,teleop,defendMovement,robot,6,1,1,0.0
551,6503,teleop,pickupGearFloor,robot,6,0,0,0.0
552,6503,teleop,pickupGearRetrival,robot,6,3,3,0.0
553,6503,teleop,placeGear,robot,6,6,7,0.0
554,949,auto,holdFuelCapacity,robot,6,0,0,0.0
555,949,auto,holdGear,robot,6,3,3,0.0
556,949,auto,moveBaseline,robot,6,3,6,0.0
557,949,auto,placeGear,robot,6,2,5,0.0
558,949,auto,startingLocation,robot,6,0,0,0.0
559,949,finish,pushTouchPad,robot,6,2,2,0.0
560,949,teleop,defendMovement,robot,6,3,3,0.0
561,949,teleop,pickupFuelFloor,robot,6,0,0,0.0
562,949,teleop,pickupFuelHopper,robot,6,0,0,0.0
563,949,teleop,pickupGearFloor,robot,6,0,0,0.0
564,949,teleop,pickupGearRetrival,robot,6,4,4,0.0
565,949,teleop,placeGear,robot,6,6,15,0.0